config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :users do
    collection do
      post :import
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
require 'csv'

class User < ApplicationRecord
  scope :with_name, ->(search_term) {
    where(name: search_term)
  }

  def self.import_csv_file(file)
    CSV.foreach(file.path, headers: true) do |row|
      User.create!(row.to_hash)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper_method :sort_column, :sort_direction

  def index
    @users = User.all
    @users = @users.with_name(params[:search]) unless params[:search].blank?
    @users = @users.order(sort_column + " " + sort_direction)

    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

  def import
    User.import_csv_file params[:file]
    redirect_to users_path, notice: "Data imported"
  rescue => ex
    redirect_to users_path, notice: "Data can't imported #{ex}"
  end

  private

  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {sort: column, direction: direction}, {class: "sort_link"}
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTestVisit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_user.html.slim
tr
  td= user.name
  td= user.date
  td= user.number
  td= user.description

app/views/users/index.html.slim
= flash[:notice]
= form_tag import_users_path, multipart: true do
  = file_field_tag :file
  = submit_tag "Import"

.user-list
  h1 User lists
  = form_tag users_path, method: :get, id: "users_search" do |f|
    = text_field_tag :search
    = submit_tag "Search"

  table
    thead
      tr
        th= sortable "name"
        th= sortable "date"
        th= sortable "number"
        th= sortable "description"

    tbody#users
      = render @users || "empty_list"

app/views/welcome/index.html.slim
h1 Visit.org Sample Project
p
  | Please complete the items on the checklist.
  
  span<> = link_to 'This is the CSV to use.', 'test.csv'

h3 Checklist
ol
  li Create model to store CSV data
  li Upload CSV via a form
  li Save CSV records to database
  li Display success/error message
  li Display users in table